### ISSUE TITLE
Installation instructions for Linux (Ubuntu)

### ISSUE THREAD

**Issue by chuong** [kenmazaika/firehose-vagrant#5]
Is the instructions for Mac applicable to Linux?
Thanks

**Comment by kenmazaika** [comment]
If you're on Ubuntu, I'd probably suggest you install things locally with these instructions:
https://github.com/FirehoseWeekend/install-guide/blob/master/ubuntu.md

You can get the vagrant setup to work with similar instructions to the mac, but it takes a bit more effort.
